# Generated by Django 4.1.3 on 2022-11-29 03:15

from django.db import migrations


def populate_status(apps, schema_editor):
    statuses = {
        "todo": "Task to be done.",
        "progress": "Currently working on it.",
        "done": "Task is done.",
    }
    Status = apps.get_model("issues", "Status")
    for name, desc in statuses.items():
        status = Status(name=name, description=desc)
        status.save()


def populate_priority(apps, schema_editor):
    priorities = {
        "low": "Low priority.",
        "medium": "Medium priority.",
        "high": "High priority.",
    }
    Priority = apps.get_model("issues", "Priority")
    for name, desc in priorities.items():
        priority = Priority(name=name, description=desc)
        priority.save()


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_status),
        migrations.RunPython(populate_priority),
    ]
